language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

before_install:
  - gem install bundler --version=1.17.3

script: bundle exec rake

deploy:
  provider: rubygems
  api_key: "$GEM_API_KEY"
  gemspec: "configcat.gemspec"
  gem: "configcat"
  on:
    tags: true